import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { prds, prd_versions, epics, stories, tasks } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { v4 as uuidv4 } from "uuid";
import type { Proposal } from "@/lib/ai/scoped-chat-tools";

/**
 * Applies a single proposal generated by the scoped chat.
 *
 * Contract: the client sends `{ project_id, proposal }`. We:
 *   1. Validate project_id matches the target (where it can be inferred).
 *   2. Apply the change via Drizzle.
 *   3. Return the new/updated row so the UI can refresh without a refetch.
 *
 * For PRD edits we also write to `prd_versions` so the change is reversible.
 * Story/epic/task edits don't yet have version tables — that's a follow-up.
 */
export async function POST(request: Request) {
  const body = await request.json();
  const { project_id, proposal } = body as { project_id: string; proposal: Proposal };

  if (!project_id || !proposal?.kind) {
    return NextResponse.json({ error: "project_id and proposal required" }, { status: 400 });
  }

  const db = await getDb();

  try {
    switch (proposal.kind) {
      case "edit_prd_section": {
        const prd = await db.select().from(prds).where(eq(prds.project_id, project_id)).get();
        if (!prd) return NextResponse.json({ error: "PRD not found" }, { status: 404 });

        const content = JSON.parse(prd.content) as Record<
          string,
          { title?: string; content: string }
        >;
        const section = content[proposal.section_key];
        if (!section) {
          return NextResponse.json(
            { error: `Unknown section: ${proposal.section_key}` },
            { status: 400 }
          );
        }

        // Snapshot prior PRD into prd_versions for undo.
        await db
          .insert(prd_versions)
          .values({
            id: uuidv4(),
            prd_id: prd.id,
            content: prd.content,
            version: (prd.version ?? 1),
            change_summary: `Edit ${proposal.section_key}: ${proposal.rationale.slice(0, 200)}`,
            created_at: new Date().toISOString(),
          })
          .run();

        content[proposal.section_key] = {
          ...section,
          content: proposal.new_content,
        };

        await db
          .update(prds)
          .set({ content: JSON.stringify(content), version: (prd.version ?? 1) + 1 })
          .where(eq(prds.id, prd.id))
          .run();

        return NextResponse.json({ ok: true, kind: proposal.kind, section_key: proposal.section_key });
      }

      case "create_epic": {
        const id = uuidv4();
        await db
          .insert(epics)
          .values({
            id,
            project_id,
            title: proposal.title,
            description: proposal.description || null,
            objective_ids: JSON.stringify([]),
            status: "backlog",
            phase: proposal.phase || "mvp",
            sort_order: 999,
            created_at: new Date().toISOString(),
          })
          .run();
        return NextResponse.json({ ok: true, kind: proposal.kind, id });
      }

      case "edit_epic": {
        const epic = await db.select().from(epics).where(eq(epics.id, proposal.id)).get();
        if (!epic || epic.project_id !== project_id) {
          return NextResponse.json({ error: "Epic not found in this project" }, { status: 404 });
        }
        const c = proposal.changes;
        await db
          .update(epics)
          .set({
            title: c.title ?? epic.title,
            description: c.description ?? epic.description,
            phase: c.phase ?? epic.phase,
            status: c.status ?? epic.status,
            technical_context: c.technical_context ?? epic.technical_context,
          })
          .where(eq(epics.id, proposal.id))
          .run();
        return NextResponse.json({ ok: true, kind: proposal.kind, id: proposal.id });
      }

      case "create_story": {
        // Confirm epic belongs to the project.
        const epic = await db.select().from(epics).where(eq(epics.id, proposal.epic_id)).get();
        if (!epic || epic.project_id !== project_id) {
          return NextResponse.json(
            { error: "Epic not found in this project" },
            { status: 400 }
          );
        }
        const id = uuidv4();
        await db
          .insert(stories)
          .values({
            id,
            epic_id: proposal.epic_id,
            project_id,
            title: proposal.title,
            description: proposal.description || null,
            acceptance_criteria: JSON.stringify(proposal.acceptance_criteria || []),
            story_points: proposal.story_points ?? null,
            priority: proposal.priority || "medium",
            moscow: proposal.moscow || "should_have",
            edge_cases: JSON.stringify([]),
            status: "backlog",
            sort_order: 999,
            created_at: new Date().toISOString(),
          })
          .run();
        return NextResponse.json({ ok: true, kind: proposal.kind, id });
      }

      case "edit_story": {
        const story = await db.select().from(stories).where(eq(stories.id, proposal.id)).get();
        if (!story || story.project_id !== project_id) {
          return NextResponse.json({ error: "Story not found in this project" }, { status: 404 });
        }
        const c = proposal.changes;
        await db
          .update(stories)
          .set({
            title: c.title ?? story.title,
            description: c.description ?? story.description,
            acceptance_criteria:
              c.acceptance_criteria !== undefined
                ? JSON.stringify(c.acceptance_criteria)
                : story.acceptance_criteria,
            story_points: c.story_points ?? story.story_points,
            priority: c.priority ?? story.priority,
            moscow: c.moscow ?? story.moscow,
            status: c.status ?? story.status,
          })
          .where(eq(stories.id, proposal.id))
          .run();
        return NextResponse.json({ ok: true, kind: proposal.kind, id: proposal.id });
      }

      case "create_task": {
        const story = await db.select().from(stories).where(eq(stories.id, proposal.story_id)).get();
        if (!story || story.project_id !== project_id) {
          return NextResponse.json({ error: "Story not found in this project" }, { status: 400 });
        }
        const id = uuidv4();
        await db
          .insert(tasks)
          .values({
            id,
            story_id: proposal.story_id,
            project_id,
            title: proposal.title,
            description: proposal.description || null,
            technical_details: proposal.technical_details || null,
            estimated_hours: proposal.estimated_hours ?? null,
            labels: JSON.stringify(proposal.labels || []),
            status: "todo",
            sort_order: 999,
            created_at: new Date().toISOString(),
          })
          .run();
        return NextResponse.json({ ok: true, kind: proposal.kind, id });
      }

      case "edit_task": {
        const task = await db.select().from(tasks).where(eq(tasks.id, proposal.id)).get();
        if (!task || task.project_id !== project_id) {
          return NextResponse.json({ error: "Task not found in this project" }, { status: 404 });
        }
        const c = proposal.changes;
        await db
          .update(tasks)
          .set({
            title: c.title ?? task.title,
            description: c.description ?? task.description,
            technical_details: c.technical_details ?? task.technical_details,
            estimated_hours: c.estimated_hours ?? task.estimated_hours,
            labels: c.labels !== undefined ? JSON.stringify(c.labels) : task.labels,
            status: c.status ?? task.status,
          })
          .where(eq(tasks.id, proposal.id))
          .run();
        return NextResponse.json({ ok: true, kind: proposal.kind, id: proposal.id });
      }

      default: {
        // Exhaustiveness guard
        const _exhaustive: never = proposal;
        return NextResponse.json({ error: `Unknown proposal kind: ${(_exhaustive as Proposal).kind}` }, { status: 400 });
      }
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error("[proposals/apply] error:", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
